import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <p className="flex justify-center">
          Free designs in 24 hours, get started now!
        </p>
        <div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        {children}
      </body>
    </html>
  );
}
